#!/bin/bash

APP="atto_link"
BUILD_HOST="68.183.100.121"
BUILD_USER="deploy"
BUILD_AT="/tmp/edeliver/$APP/builds/"

START_DEPLOY=true
CLEAN_DEPLOY=true


PRODUCTION_HOSTS="68.183.100.121"
PRODUCTION_USER="deploy"
DELIVER_TO="home/deploy/phx/apps/"
AUTO_VERSION=revision


pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/deploy/app_config/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
    [ -f ~/.profile ] && source ~/.profile
    set -e
    # prepare something
    mkdir -p priv/static

    mkdir -p '$BUILD_AT'

    ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
    "
  fi
}

